feat: alert context
pesto-students/batch-10-tripen pull request #79
Opened 2019-09-26 11:02 UTC by SarthakC

## PR Checklist
Please check that your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/pesto-students/batch-10-tripen/wiki/Commit-message-guidelines)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] GIFs/Videos/Images added (compulsory for frontend changes)

## PR Type
What kind of change does this PR introduce? 

- [ ] Bugfix
- [ ] Feature
- [ ] Tests changed / added / updated
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Infrastructure changes
- [ ] Dependency upgrade
- [ ] Other... Please describe:

## Issue Number: 
#72 

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2019-09-29 01:55 UTC, karansapolia approved these changes
Recommend always including a gif of the functionality. Would appreciate one for this PR too :slightly_smiling_face:

2019-09-30 11:16 UTC, p-racoon approved these changes
need KT on this

2019-09-30 12:34 UTC, rishabh1403 requested changes
- remove redundant comments
- add validations
- add server url as constants
- add line breaks 

fix these things at all places

2019-09-30 12:34 UTC, rishabh1403 commented on client/src/context/alert/AlertState.js
> +  const setAlert = (msg, type, timeout = 5000) => {
nice :)

2019-09-30 12:34 UTC, rishabh1403 commented on client/src/context/auth/AuthState.js
> +      const res = await axios.get('/api/auth');
this api request will not work if client and server are hosted cross domain.
have a constant with server url and make a request accordingly :)

2019-09-30 12:34 UTC, rishabh1403 commented on client/src/context/auth/AuthState.js
> +      const res = await axios.post('/api/users', formData, config);
same as above... cross domain

2019-09-30 12:34 UTC, rishabh1403 commented on client/src/context/auth/AuthState.js
> +        payload: err.response.data.msg,
what if err doesn't have response...response doesn't have data and data doesn't have mgs? hahah
Validations on dot operators please :) , else your catch will throw errors

2019-09-30 12:34 UTC, rishabh1403 commented on client/src/context/auth/AuthState.js
> +  // Logout
this comment is redundant. The function name is self-explanatory

2019-09-30 12:34 UTC, rishabh1403 commented on client/src/context/auth/authReducer.js
> +  switch (action.type) {
add line breaks, unreadable code

2022-03-31 11:13 UTC, closed without merging

2022-03-31 11:17 UTC, p-racoon commented
Lol 😂

2022-03-31 11:31 UTC, rishabh1403 commented
old memories